Update Qemu for checkmk 2
Fixed an issue that the check isn't running on CheckMK 2.0.0p23:
TypeError: inventory_qemu() missing 1 required positional argument: 'info'